site_url: https://aldermann.github.io
media_folder: static/assets
public_folder: /assets
collections:
    - name: blog
      label: Blog
      folder: src/posts
      create: true
      format: yaml-frontmatter
      fields:
          - name: date
            label: Date
            widget: datetime
          - name: title
            label: Title
          - name: description
            label: Description
            widget: text
          - name: keyword
            label: Keywords
            widget: list
          - name: body
            label: Body
            widget: markdown
backend:
    name: github
    repo: aldermann/aldermann.github.io
    branch: develop
