site_url: https://aldermann.github.io
media_folder: static/assets
public_folder: /assets
collections:
    - name: blog
      label: Blog
      folder: posts
      create: true
      format: yaml-frontmatter
      path: "{{series}}{{slug}}/index"
      media_folder: ''
      public_folder: ''
      fields:
          - name: date
            label: Date
            widget: datetime

          - name: series
            label: Series
            widget: string
            required: false
            pattern: ['^[\w\d_]+/$', "The series should be word and underscore and ended with /"]

          - name: title
            label: Title

          - name: description
            label: Description
            widget: text
            required: false

          - name: keyword
            label: Keywords
            widget: list
            required: false

          - name: body
            label: Body
            widget: markdown
backend:
    name: github
    repo: aldermann/aldermann.github.io
    branch: develop
publish_mode: editorial_workflow
show_preview_links: false
